Спринт 15, попытка 1
arcyandex/java-shareit pull request #5
Opened 2022-09-08 22:55 UTC by arcyandex

2022-09-09 05:14 UTC, eugene-lenkevich requested changes
Привет, Алексей, спасибо за PR

В целом все супер :)
У меня есть некоторое предложение по рефакторингу, посмотри комментарии ниже, пожалуйста

2022-09-09 05:14 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingsByState.java
> +        switch (state) {
1. Вижу что фильтрация происходит на стороне сервера, это не гут, данных может быть очень много, делать выборку данных стоит на стороне БД, она это умеет гораздо лучше :)
И вообще, неплохо бы написать тест с базой данных (@DataJpaTest) на этот класс, для этого опять таки сделав его спринговым бином, убрать все статические методы, забить тестовые данные и проверить как работает выборка 

2.
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

Спрашивай в слаке, если что :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2022-09-14 23:11 UTC, arcyandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (state.equals("UNSUPPORTED_STATUS")) {
Сделано

2022-09-14 23:12 UTC, arcyandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public static BookingDto toBookingDto(Booking booking) {
Тоже готово

2022-09-14 23:15 UTC, arcyandex commented on src/main/java/ru/practicum/shareit/booking/service/BookingsByState.java
> +        switch (state) {
Вот тут сделал частично:

1. Фильтрацию перенес на сторону БД
2. Дополнил тесты
3. Убрал класс Bookings By State и перенес логику в сервис

Автотесты завалились, т.к. использовал короткий синтаксис switch, которого нет в Java 11.
Но паттерн не применял, т.к. обработчики везде в одну строчку и везде разные - получается сложнее для понимания.

2022-09-15 06:07 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingsByState.java
> +        switch (state) {
Паттерн чисто для информации, в нашем случае да, он будет громоздким :)

2022-09-15 06:08 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-09-24 11:40 UTC, merged